trigger: none

pool:
  name: akhileshpool

variables:
  terraformVersion: '1.15.6'
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

stages:
- stage: DEV
  displayName: "Terraform DEV Plan & Publish"
  jobs:
  - job: Terraform_DEV_Plan
    displayName: "Terraform DEV Plan"
    steps:

    # 1. Install Terraform
    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: $(terraformVersion)

    # 2. Terraform Security Scan (tfsec)
    - script: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        tfsec $(terraformWorkingDirectory)
      displayName: "Terraform tfsec Scan"

    # # 3. Terraform Format Check
    # - script: |
    #     terraform fmt -check -recursive
    #   workingDirectory: $(terraformWorkingDirectory)
    #   displayName: "Terraform Format Check"

    # 4. Terraform Init
    - task: TerraformTask@5
      displayName: "Terraform Init DEV"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(terraformWorkingDirectory)
        backendServiceArm: 'akhileshserviveconnection'
        backendAzureRmResourceGroupName: 'akhileshtestpip'
        backendAzureRmStorageAccountName: 'akhileshstoragepipi'
        backendAzureRmContainerName: 'akhileshcanttest'
        backendAzureRmKey: 'dev.tfstate'

    # 5. Terraform Validate
    - task: TerraformTask@5
      displayName: "Terraform Validate DEV"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(terraformWorkingDirectory)

    # 6. Terraform Plan (Saves the execution plan to tfplan)
    - task: TerraformTask@5
      displayName: "Terraform Plan DEV"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: 'akhileshserviveconnection'
        commandOptions: '-out=tfplan'

    # 7. Publish Terraform Plan (tfplan) as a Pipeline Artifact
    - task: PublishPipelineArtifact@1
      displayName: "Publish Terraform Plan Artifact"
      inputs:
        targetPath: '$(terraformWorkingDirectory)/tfplan'
        artifact: 'terraform-plan'
        publishLocation: 'pipeline'