trigger: none

pool:
  name: akhileshpool

variables:
  terraformVersion: '1.15.6'
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

stages:
- stage: DEV
  displayName: "Terraform DEV Deployment"
  jobs:
  - job: Terraform_DEV
    displayName: "Terraform DEV Apply"
    steps:

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        tfsec $(terraformWorkingDirectory)
      displayName: "Terraform tfsec Scan"

    - script: |
        terraform fmt -check -recursive
      workingDirectory: $(terraformWorkingDirectory)
      displayName: "Terraform Format Check"

    - task: TerraformTask@5
      displayName: "Terraform Init DEV"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(terraformWorkingDirectory)
        backendServiceArm: 'akhileshserviveconnection'
        backendAzureRmResourceGroupName: 'akhileshtestpip'
        backendAzureRmStorageAccountName: 'akhileshstoragepipi'
        backendAzureRmContainerName: 'akhileshcanttest'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      displayName: "Terraform Validate DEV"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(terraformWorkingDirectory)

    - task: TerraformTask@5
      displayName: "Terraform Plan DEV"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: 'akhileshserviveconnection'
        commandOptions: '-out=tfplan'

    - task: TerraformTask@5
      displayName: "Terraform Apply DEV AUTO APPROVE"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: 'akhileshserviveconnection'
        commandOptions: 'tfplan -auto-approve'